baseURL = 'https://jsheunis.github.io/distribits-2024-website/'
languageCode = 'en-us'
title = 'distribits'
theme = "PaperMod"

# see https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml

[params]
  [params.profileMode]
    enabled = true
    title = 'Connecting data islands and lakes'
    subtitle = "supported by DataLad and git-annex"
    imageUrl = "pics/distribits_logo_a.svg"
    imageTitle = "distribits_logo"
    imageWidth = 800

  # repeat as many times as needed
  # icon names -> grep icon_name themes/PaperMod/layouts/partials/svg.html
  [[params.socialIcons]]
    name = "mastodon"
    url = "https://fosstodon.org/@datalad"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/datalad"


git add public/about/index.html
git add public/assets/css/stylesheet.273e606b7053fb716c5b30f84e1b1c427177bef547a1660fa668d76b9ae1b760.css
git add public/assets/js/highlight.f413e19d0714851f6474e7ee9632408e58ac146fbdbe62747134bea2fa3415e0.js
git add public/categories/index.html
git add public/categories/index.xml
git add public/index.html
git add public/index.xml
git add public/location/index.html
git add public/pics/distribits_logo_a.svg
git add public/registration/index.html
git add public/schedule/index.html
git add public/sitemap.xml
git add public/tags/index.html
git add public/tags/index.xml